# fichier de configuration au SGBD postgreSQL

POSTGRESQL_SERVER = "bd-pedago.univ-lyon1.fr"
POSTGRESQL_USER = "p2301612"  
POSTGRESQL_PASSWORD = "Flatness%Bruising_63"  
POSTGRESQL_DATABASE = "p2301612"  
POSTGRESQL_SCHEMA = "projet" 
